# A first worflow to play
name: My first Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  first_job:
    name: My first Job
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - run: tree........
      - name: Obteniendo info del contexto
        run: |
          echo "Actor con curly braces :   ${{ github.actor }}"
          echo "Actor con usd sign : $GITHUB_ACTOR" 
          echo "SHA is : $GITHUB_SHA"
          echo "EVent Name : $GITHUB_EVENT_NAME"
          echo "by Alex"
      - name: Echo branch
        run:  echo "${{ github.event.base_ref }}"
